# Generated by Django 5.1.3 on 2024-11-14 11:44

import musicPlayer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=musicPlayer.models.generateRoomCode, max_length=8, unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=50)),
                ('guest_control', models.BooleanField(default=False)),
                ('votes_to_skip', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
